[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.104.3"

[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"
